services:

  database:
    container_name: qb-database-dev
    image: postgres:15-alpine
    volumes:
      - qb_postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Alchemy
    restart: always
    ports:
      - "5432:5432"
    networks:
      - qb_custom
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  qb_custom:
    driver: bridge

volumes:
  qb_postgres:
