services:

  database:
    container_name: qb-database
    image: postgres:15-alpine
    volumes:
      - qb_postgres:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  backend:
    container_name: qb-backend
    image: sergei1m/qb_challenge:fastapi
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - qb_bk_data:/app/data/
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - database


  nginx:
    container_name: qb-nginx
    image: nginx:1.24-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - qb_bk_data:/usr/share/nginx/html/bk_data/
    depends_on:
      - backend


volumes:
  qb_bk_data:
  qb_postgres:
